<?php

namespace app\models;
use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
    public static function tableName()
    {
        return 'category'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['title', 'descreption', 'keywords'], 'required'],
            [['title', 'descreption', 'keywords'], 'string'],
        ]; // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'title' => 'Заголовок',
            'descreption' => 'Описание',
            'keywords' => 'Ключивые слова',
        ]; // TODO: Change the autogenerated stub
    }
}
